//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleManager.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessExceptionMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessExceptionMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeopleManager.Domain.Resources.BusinessExceptionMsg", typeof(BusinessExceptionMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string EXC0001 {
            get {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma pessoa cadastrado com o e-mail informado..
        /// </summary>
        public static string EXC0002 {
            get {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha inválidos..
        /// </summary>
        public static string EXC0003 {
            get {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais inválidas..
        /// </summary>
        public static string EXC0004 {
            get {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa não encontrada..
        /// </summary>
        public static string EXC0005 {
            get {
                return ResourceManager.GetString("EXC0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário atualizado com sucesso..
        /// </summary>
        public static string EXC0006 {
            get {
                return ResourceManager.GetString("EXC0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa já cadastrada com o CPF informado..
        /// </summary>
        public static string EXC0007 {
            get {
                return ResourceManager.GetString("EXC0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string EXC0008 {
            get {
                return ResourceManager.GetString("EXC0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é inválido..
        /// </summary>
        public static string EXC0009 {
            get {
                return ResourceManager.GetString("EXC0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não existe ou não pertence ao usuário autenticado..
        /// </summary>
        public static string EXC0010 {
            get {
                return ResourceManager.GetString("EXC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente deletado com sucesso..
        /// </summary>
        public static string EXC0011 {
            get {
                return ResourceManager.GetString("EXC0011", resourceCulture);
            }
        }
    }
}
